[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arxiv-agent"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88  # or 79 if you want strict PEP8
target-version = "py313"  # match your Python version

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "UP",  # pyupgrade (modernize syntax)
    "B",
    "ANN"   # bugbear (common bug patterns)
]
ignore = []

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"